flowers_images_path: '/home/.data/102flowers/'
flowers_embedding_path: '/home/.data/flowers_icml/'
flowers_text_path: '/home/.data/cvpr2016_flowers/text_c10/'
flowers_dataset_path: '/home/.data/flowers.hdf5'

flowers_val_split_path: '/home/.data/flowers_icml/valclasses.txt'
flowers_train_split_path: '/home/.data/flowers_icml/trainclasses.txt'
flowers_test_split_path: '/home/.data/flowers_icml/testclasses.txt'

# Birds CUB dataset
birds_images_path: '/home/data/CUB_200_2011/CUB_200_2011/images/'
birds_embedding_path: '/home/data/cub_icml/'
birds_text_path: '/home/data/cvpr2016_cub/text_c10/'
birds_dataset_path: '/home/birds.hdf5'
val_split_path: '/home/data/cub_icml/valclasses.txt'
train_split_path: '/home/data/cub_icml/trainclasses.txt'
test_split_path: '/home/data/cub_icml/testclasses.txt' 
